logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://20.214.202.113:3306/item?serverTimezone=Asia/Seoul
    username: adminuser
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/item?serverTimezone=Asia/Seoul
#    username: root
#    password: sk002760
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql : true
    generate-ddl: true
#  sql:
#    init:
#      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true

serverUrl: https://d565-202-31-138-11.ngrok-free.app